### PR TITLE
Deno support

### PR DESCRIPTION
**Pull request by alexjeffburke**

### CODE REVIEW

**Comment by alexjeffburke** [comment]
@sunesimonsen at the moment use of the esm module requires an explicit import - from what I can tell, that’s still relatively common. The inly issue I can see with adding it to package.json is various other tools will quietly switch over - and I’ve seen that have consequences. I’ve seen some libraries revert that change recently.

I think I’d suggest we get this in and then the asset will be in the package - and we could follow up with the package level entry at our leisure, but see why you think :)

**Comment by sunesimonsen** [comment]
Yes lets just throw it in.

**Comment by sunesimonsen** [comment]
@alexjeffburke I added you as owner on the magicpen package, so you can just release it as a minor.

**Comment by alexjeffburke** [comment]
@sunesimonsen great! I’d gladly merge and release but I’m not sure I’ve permissions enough :)

**Comment by sunesimonsen** [comment]
@alexjeffburke I have added you as a contributor.

**Pull request merged**
