### PR TITLE
installPlugin => use, allow functions as plugins

### PR DESCRIPTION
**Pull request by papandreou**
Port of https://github.com/unexpectedjs/unexpected/pull/193

### CODE REVIEW

**Comment by sunesimonsen** [comment]
Looks good, could you also rename the method in the readme, then I'll merge it.

**Comment by papandreou** [comment]
Done.

Maybe we should also rename `installTheme` to something shorter for consistency.

**Comment by sunesimonsen** [comment]
`useTheme` might make sense.

**Comment by sunesimonsen** [comment]
Thank you very much, it looks great.

**Pull request merged**
